name: Python formatting PEP8
on: #sg
  push:
    branches: [master, "*"]
  pull_request:
    branches: [master, "*"]
jobs:
  print:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          pytho-version: 3.9
      - name: ls
        run: |
          ls .
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run checking
        run: |
          flake8 webface.py
      - name: Install requirements
        run: |
          pip install -r requirements.txt
        
